### ISSUE TITLE
The Roadmap 🚧 ☢️ 🚀

### ISSUE THREAD

**Issue by hmans** [hmans/trinity#39]
Trinity aims at integrating a curated selection of libraries into a _framework_ for rapidly building 3D (and possibly 2D) games on the web. 

## Things Trinity MUST Provide 🌟

- [x] Integrate with Three.js for 3D rendering
- [x] Provide React glue so this can be done declaratively
- [ ] #41

## Things Trinity SHOULD Provide 😊

- [ ] Macro game state with a Router-like DSL (possibly built on top of [@xstate/fsm](https://github.com/statelyai/xstate/tree/main/packages/xstate-fsm))
- [ ] #40
- [ ] Integrate with a 3D physics engine (preferably [Rapier](https://rapier.rs/))
- [ ] React glue for audio (using Three.js' own audio primitives.)
- [x] React glue for composable render pipelines, with support for Three.js' built-in effect passes and shaders.
- [ ] CPU-based Particle Effects (possibly through [Sprudel](https://github.com/joergjaeckel/sprudel), but maybe its own system)
  - Note: I have explored this to some extent in [particulous](https://github.com/hmans/particulous).
- [ ] HTML-based screen-space UI (probably through `@hmans/ui` or similar.)

## Things Trinity MAY Provide 🤷‍♀️

- [ ] Put miniplex-powered ECS front and center.
  - Advantage: ECS and miniplex are cool, and we're already using it for physics and VFX!
  - Disadvantage: people might want to use a different ECS. Is this really a disadvantage, considering no-one is stopping you from loading _another_ ECS library into the project? Probably not.
- [ ] GPU-based Particle Effects
- [ ] Support 2D games (both in terms of rendering, but also physics)
  - Note: Rapier has a [2D version](https://www.npmjs.com/package/@dimforge/rapier2d-compat), but it's an entirely separate package from the 3D one.

## Things Trinity WILL PROBABLY NOT Provide 🚫

- Advanced integration with non-WebGL DOM content
- VR/AR/XR support. I don't want to rule it out completely, but the focus for Trinity is, for now, on-screen experiences.
- React Native/Mobile support. If there is a low-friction way to support this, let's go for it, but Trinity very confidently aims for web and web only.
